# Numpy Random Package



<img src='NJP-Symbols.jpg' />

This is an investigation in to the Numpy random package. This investigation is divided in to four parts see links below. There is also a Reference section that provides a list of links used in this investigation.

[1. Introduction to Numpy random](#1.-Introduction-to-Numpy-random)

[2. Simple random data & Permutations](#2.-Simple-random-data-&-Permutations)

[3. Five Distribution Functions](#3.-Five-Distribution-Functions)

[4. Seeds in generating pseudorandom numbers](#4.-Seeds-in-generating-pseudorandom-numbers)

[References](#References)


## 1. Introduction to Numpy and Numpy random

- Numpy is a multidimensional array library, it can create and manliplate multiple sizes of arrays for example 1-dimensional, 2-dimensional 3-dimensional etc arrays.
- Numpy arrays are a very efficient incomparsion to lists for the folllowing reasons
 * Numpy uses less memory to store arrays.
 * Numpy arrays are the same data type so no type checking is required this is not a case with lists.
 * Numyy uses contigious memory blocks to store array values this allows SIMD (Single Instruction Multiple Data) vector processing to perform multiple calulations of arrays that are sequentially stored in memory, this allows for more efficent CPU usage in processing calculations for arrays. Its also allows for efficient cache usage. 
 
- Numpy random is a sub package of the Numpy
- Numpy random package is a way of generating random numbers or psuedo random numbers for computers
- Generates arrays of numbers, arrays are a grouping of homogenous data types, the data element have to be of the same type.
- Usually don't use Numpy directly its usually used with other packages such as pandas or SciPy

In [1]:
# To start this investigation the Numpy package is imported as np & matplotlib.pyplot package is imported a plt

import numpy as np
import matplotlib.pyplot as plt


* The next few functions will demonstrate how Numpy generates simple arrays and functions that will give information on these arrays.

In [38]:
#Creating array and assign it to x, created integers as 16bit (2 Bytes) instead of 32int default (4bytes)
x = np.array([2, 3], dtype='int16')

In [39]:
#Prints the 1st value of array x
x[0]

2

In [40]:
#Prints the 2nd value of array x
x[1]

3

In [41]:
#Print the dimension of array x, dimension of the array is 1D
x.ndim

1

In [42]:
#Prints array size as defined in above, if dtype int16 is not specified 'int32' is default for integers 
x.dtype

dtype('int16')

In [44]:
#Prints the item size of the array in bytes, as its int 16 each value is 2 Bytes
x.itemsize

2

In [46]:
# Prints the total size of the array in Bytes. This is 4 Bytes, ie two 16 bit integer values.
x.nbytes

4

In [3]:
# Create an array assign it to x
x = np.array([[1,2,3,4],[5,6,7,8]])
print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
#Prints out the shape of array x two rows with 4 columns
np.shape(x)

(2, 4)

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
y = np.arange(2, 5, 0.5)
print(y)

[2.  2.5 3.  3.5 4.  4.5]


In [ ]:
#This is a random (float) number generator of uniform distribution over [0,1) in the example the array dimensions are 4 rows x 3 columns
a = np.random.rand(4,3)


## 2. Simple random data & Permutations

In this section we will investigate a few simple random data and Permutation functions.

### 2.1 Simple random data

To illustrate simple random data in numpy the following functions are discussed

- *numpy.random.rand*
- *numpy.random.randn*

#### random.rand
This is part of the simple random data sampling, this function uses uniform distribution, the plots show the difference between it and random.randn which uses normal or Gaussian distribution

In [ ]:
#If no argument is given a single floating point number is returned
np.random.rand()

In [ ]:
# if one one number is given it returns an array of a single row containing that amount of elements
%matplotlib inline
rand = np.random.rand(1000)
print(rand)
plt.hist(rand)
plt.title('Uniform Distribution of 1000 Numbers')
plt.show()

### random.randn

In [ ]:
#This function returns a floating point number from the normal(Gaussian) distribution, returns a floating point number in from the range (0,1]
np.random.randn(4,3)

In [ ]:
#If no argument is given a single floating point number is returned
np.random.randn()

In [ ]:
# if one one number is given it returns an array of a single row containing that amount of elements
%matplotlib inline
randn = np.random.randn(1000)
print(randn)
plt.hist(randn)
plt.title('Gaussian Distribution of 1000 Numbers')
plt.show()

The numpy.random.randint code below was taken from [SciPy random.randint](https://docs.scipy.org/doc/numpy/reference/random/index.html?highlight=numpy%20random#module-numpy.random)

In [ ]:
# numpy random.randint generates random integers of uniform distribution over [0,1), this size of the array is 10 items.

a = np.random.randint(low = 0, high = 7, size = 10)

print(a)
print(a.size)
print(a.ndim)
print(a.dtype)

### 2.2 Permutations

## 3. Five Distribution Functions

## 4. Seeds in generating pseudorandom numbers

## References

 * Scipy Numpy Random Documentation https://docs.scipy.org/doc/numpy-1.16.1/reference/routines.random.html 
 * Free Code Camp https://www.freecodecamp.org
 * Numpy Basics https://docs.scipy.org/doc/numpy-1.16.0/user/basics.html
 * Creating Arrays in Numpy https://docs.scipy.org/doc/numpy-1.13.0/user/basics.creation.html
 * Creating links using Markdown https://stackoverflow.com/questions/2822089/how-to-link-to-part-of-the-same-document-in-markdown
 * Jupyter https://jupyter.org/